### PR TITLE
Adds Drop calculations to MICSR

### PR DESCRIPTION
**Pull request by ChangedNameTo**
Adds drop calculations to MICSR. I'm not sure how to handle the item doubling modifiers, and leave that to the maintainer 😛

### CODE REVIEW

**Comment by gmiclotte** [comment]
Hi, great work!

Something's off with rune knights, rune scims are 1/160 afaict



Some other changes I'd make based on a first view, but not necessarily before releasing this:
- [ ] recompute "drops/" when selecting a different item, also update the selected view and the plot. Now this requires a resim.
- [ ] merge "GP Options" and "Drop Chance Options", call it "Drop Options".
- [ ] add some filters to the drop down
 - should never show items that are not monster drops
 - could have a filter based on current selected monster
 - could have a filter based on items that you have not discovered yet
- [ ] clean up the drop down entries. This might no longer be necessary when non-drop items are filtered.

- [ ] add a popup for drop selection similar to gear selection. Keeping the drop down might be nice too for name-based searching.
- [ ] add drop doubling by multiplying by `1 + double chance`. Double check combat.js to make sure we get all the involved modifiers.
- [ ] add chest loot. Right now you get `0` rates for `Bank Slot Token` for example.

If you'd like to do any of these, then let me know, if not, I'll see what I can do and throw the rest in an issue.

**Comment by ChangedNameTo** [comment]
Sounds good, I'll take the following:

- [ ] Merge "Drop Options"
- [ ] Filter out items that are not dropped by monsters
- [ ] Add chest loot
- [ ] Add drop doubling
- [ ] Recompute on new item selection

Some comments on the above:

- could have a filter based on current selected monster
Can you expand on this?
- could have a filter based on items that you have not discovered yet/ add a popup for drop selection similar to gear selection. Keeping the drop down might be nice too for name-based searching.
This seems like a really good idea, but would likely need to change how the item selection works from being a single value to being a multiselect. I think out of scope for my first attempt.

**Comment by gmiclotte** [comment]
> could have a filter based on current selected monster

I was thinking about something like this, not sure if it's actually a useful idea :upside_down_face:

**Comment by ChangedNameTo** [comment]
@gmiclotte I think I'm about done with this for now, I want to get back to SEMI prelaunch. Couple of notes:
* Didn't get around to implementing two of the checkboxes. Chest loot is probably doable but a pain, I'm not sure if I want to refactor. Recompute on item change is possible, but would require a rewrite of the function `getDropRate` to add some caching there.
* I'm still not confident that the numbers are right on the drops/h. I'm getting simmed values of 1.9/hr in the sim, but 1.14/hr in reality for ku-tul. Obviously this could just be bad rng, just a heads up

**Comment by gmiclotte** [comment]
Concluding with ef2215f I now implemented all the suggestions above, except for the "popup for drop selection similar to gear selection".

**Pull request merged**
